x-mobilitydb-base: &mobilitydb-base
  build:
    context: .
    dockerfile: dockerfile
  image: my-mobilitydb-citus-image:latest

services:
  coordinator:
    <<: *mobilitydb-base
    container_name: coordinator
    ports:
      - "5432:5432"
    environment:
      - PGPASSWORD=password
      - POSTGRES_PASSWORD=password
      - WORKER_NODES=worker1:5432,worker2:5432
        # volumes:
        #   - ./start-coordinator.sh:/docker-entrypoint-init.d/start-coordinator.sh
        # command: ["bash", "/docker-entrypoint-init.d/start-coordinator.sh"]
    depends_on:
      - worker1
      - worker2
    networks:
      - citus

  worker1:
    <<: *mobilitydb-base
    container_name: worker1
    environment:
      - PGPASSWORD=password
      - POSTGRES_PASSWORD=password
    networks:
      - citus

  worker2:
    <<: *mobilitydb-base
    container_name: worker2
    environment:
      - PGPASSWORD=password
      - POSTGRES_PASSWORD=password
    networks:
      - citus

networks:
  citus:
